# Generated by Django 2.2.1 on 2019-05-03 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='dateEntry',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
